version: '3.8'

services:
  echo:
    image: crossbario/autobahn-testsuite:latest
    command: wstest -m echoserver -w ws://0.0.0.0:9000

  fuzzingserver:
    image: crossbario/autobahn-testsuite:latest
    volumes:
    - ./autobahn/config:/config
    - ./autobahn/reports:/reports

  app:
    image: elixir:1.12.0-rc.1
    environment:
    - 'ERL_AFLAGS=-kernel shell_history enabled'
    volumes:
    - ./:/app
    working_dir: /app
    command: bash -c "mix local.hex --force && mix local.rebar --force && tail -f /dev/null"
