version: '3.8'

services:
  echo:
    image: crossbario/autobahn-testsuite:latest
    command: wstest -m echoserver -w ws://0.0.0.0:9000
    ports:
    - 9000:9000

  fuzzingserver:
    image: crossbario/autobahn-testsuite:latest
    volumes:
    - ./autobahn/config:/config
    - ./autobahn/reports:/reports
    ports:
    - 9001:9001

  h2server:
    image: ruby:2.7.3-slim-buster
    volumes:
    - ./priv/h2server:/app
    working_dir: /app
    command: bash -c "apt update && apt install -y g++ make && gem install falcon async-websocket && ./config.ru"

  app:
    image: elixir:1.12.0-rc.1
    environment:
    - 'ERL_AFLAGS=-kernel shell_history enabled'
    - ECHO_HOST=echo
    - FUZZINGSERVER_HOST=fuzzingserver
    volumes:
    - ./:/app
    working_dir: /app
    command: bash -c "mix local.hex --force && mix local.rebar --force && tail -f /dev/null"
